# Generated by Django 5.0 on 2023-12-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='level',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Premium', 'Premium')], default='Standard', max_length=20),
        ),
    ]
